<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'HtTimeZone\Module'                                         => __DIR__ . '/Module.php',
  'HtTimeZone\Entity\User'                                    => __DIR__ . '/src/HtTimeZone/Entity/User.php',
  'HtTimeZone\Factory\ModuleOptionsFactory'                   => __DIR__ . '/src/HtTimeZone/Factory/ModuleOptionsFactory.php',
  'HtTimeZone\Factory\TimeZoneServiceFactory'                 => __DIR__ . '/src/HtTimeZone/Factory/TimeZoneServiceFactory.php',
  'HtTimeZone\Factory\ZfcUserTimeZoneProviderFactory'         => __DIR__ . '/src/HtTimeZone/Factory/ZfcUserTimeZoneProviderFactory.php',
  'HtTimeZone\Form\Element\Factory\TimeZoneFactory'           => __DIR__ . '/src/HtTimeZone/Form/Element/Factory/TimeZoneFactory.php',
  'HtTimeZone\Form\Element\TimeZone'                          => __DIR__ . '/src/HtTimeZone/Form/Element/TimeZone.php',
  'HtTimeZone\Options\ModuleOptions'                          => __DIR__ . '/src/HtTimeZone/Options/ModuleOptions.php',
  'HtTimeZone\Provider\TimeZoneProviderInterface'             => __DIR__ . '/src/HtTimeZone/Provider/TimeZoneProviderInterface.php',
  'HtTimeZone\Provider\ZfcUserTimeZoneProvider'               => __DIR__ . '/src/HtTimeZone/Provider/ZfcUserTimeZoneProvider.php',
  'HtTimeZone\Service\TimeZone'                               => __DIR__ . '/src/HtTimeZone/Service/TimeZone.php',
  'HtTimeZone\View\Helper\Exception\InvalidArgumentException' => __DIR__ . '/src/HtTimeZone/View/Helper/Exception/InvalidArgumentException.php',
  'HtTimeZone\View\Helper\Factory\HtTimeZoneFactory'          => __DIR__ . '/src/HtTimeZone/View/Helper/Factory/HtTimeZoneFactory.php',
  'HtTimeZone\View\Helper\HtTimeZone'                         => __DIR__ . '/src/HtTimeZone/View/Helper/HtTimeZone.php',
);
